spring.application.name=Workout
spring.datasource.url=jdbc:mysql://localhost:3306/workout
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.servlet.context-path=/api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret-key=hdjsu6r73uwiqh8763uhhghvgjffc6u73ocnyer6394uich65e4384r6dsdju387ryedbns65jdhqiwr7e
jwt.expiration=86400000
